### PR TITLE
Molecule: Add Bookworm and remove Leap 15.3

### PR DESCRIPTION
**Pull request by grisu48**
Adds Debian "Bookworm" to the molecule tests and remove Leap 15.3

### CODE REVIEW

**Comment by CaptainSifff** [comment]
looks good, but what is the reason for removing 15.3?

**Review by CaptainSifff — APPROVED** [review]
looks good to me!

**Comment by CaptainSifff** [comment]
I think it closes #1

**Comment by grisu48** [comment]
> looks good, but what is the reason for removing 15.3?

Leap 15.3 is EOL since 2023.

**Pull request merged**
